# Generated by Django 5.0.2 on 2024-02-22 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.IntegerField()),
                ('defindex', models.IntegerField()),
                ('paintseed', models.IntegerField()),
                ('rarity', models.IntegerField()),
                ('quality', models.IntegerField()),
                ('killeatervalue', models.IntegerField()),
                ('customname', models.CharField(max_length=1000)),
                ('stickers', models.JSONField()),
                ('floatvalue', models.FloatField()),
                ('imageurl', models.ImageField(upload_to=None)),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('item_name', models.CharField(max_length=1000)),
                ('weapon_type', models.CharField(max_length=1000)),
                ('origin_name', models.CharField(max_length=1000)),
                ('quality_name', models.CharField(max_length=1000)),
                ('rarity_name', models.CharField(max_length=1000)),
                ('wear_name', models.CharField(max_length=1000)),
                ('full_item_name', models.CharField(max_length=1000)),
                ('s', models.IntegerField()),
                ('a', models.IntegerField()),
                ('d', models.IntegerField()),
                ('m', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
