# Generated by Django 5.0.2 on 2024-02-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0002_alter_arma_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='customname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='full_item_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='itemid',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='arma',
            name='origin_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='quality_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='rarity_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='weapon_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='arma',
            name='wear_name',
            field=models.CharField(max_length=100),
        ),
    ]
