# Generated by Django 5.0.2 on 2024-02-22 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0003_alter_arma_customname_alter_arma_full_item_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='stickers',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='armas', to=settings.AUTH_USER_MODEL),
        ),
    ]
