# Generated by Django 5.0.2 on 2024-02-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0005_alter_arma_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='stickers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
