# Generated by Django 5.0.2 on 2024-02-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0006_alter_arma_stickers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='imageurl',
            field=models.URLField(max_length=1000),
        ),
    ]
