# Generated by Django 5.0.2 on 2024-02-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0007_alter_arma_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='killeatervalue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
