# Generated by Django 5.0.2 on 2024-02-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0008_arma_precio_alter_arma_killeatervalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='categoria',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='customname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='defindex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='floatvalue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='paintseed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='rarity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arma',
            name='s',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
