# Generated by Django 5.0.2 on 2024-05-03 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0009_arma_categoria_alter_arma_a_alter_arma_customname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arma',
        ),
    ]
