# Generated by Django 5.0.2 on 2024-05-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField()),
                ('quality', models.IntegerField(blank=True, null=True)),
                ('rarity', models.IntegerField(blank=True, null=True)),
                ('a', models.IntegerField(blank=True, null=True)),
                ('d', models.IntegerField(blank=True, null=True)),
                ('paintseed', models.IntegerField(blank=True, null=True)),
                ('defindex', models.IntegerField(blank=True, null=True)),
                ('paintindex', models.IntegerField(blank=True, null=True)),
                ('floatid', models.CharField(blank=True, max_length=255, null=True)),
                ('floatvalue', models.FloatField(blank=True, null=True)),
                ('full_item_name', models.CharField(max_length=100)),
                ('imageurl', models.URLField(max_length=1000)),
                ('max', models.FloatField(blank=True, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('quality_name', models.CharField(max_length=100)),
                ('weapon_type', models.CharField(max_length=50)),
                ('wear_name', models.CharField(max_length=100)),
                ('low_rank', models.IntegerField()),
                ('high_rank', models.IntegerField()),
                ('s', models.IntegerField(blank=True, null=True)),
                ('m', models.IntegerField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=100)),
                ('rarity_name', models.CharField(max_length=100)),
                ('origin_name', models.CharField(max_length=100)),
                ('precio', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
