# Generated by Django 5.0.2 on 2024-05-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_arma_a_alter_arma_d_alter_arma_full_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='inspect_link',
            field=models.URLField(null=True),
        ),
    ]
