# Generated by Django 5.0.2 on 2024-05-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_arma_inspect_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='owner_steamid',
            field=models.FloatField(default=76561199092801246),
        ),
    ]
