# Generated by Django 5.0.2 on 2024-05-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_arma_owner_steamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='owner_steamid',
            field=models.BigIntegerField(default=76561199092801246),
        ),
    ]
