# Generated by Django 5.0.2 on 2024-05-08 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_arma_owner_steamid'),
        ('carrito', '0002_carrito_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='carrito',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='carrito.carrito'),
        ),
    ]
