# Generated by Django 5.0.2 on 2024-05-08 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_arma_carrito'),
        ('carrito', '0002_carrito_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='carrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrito.carrito'),
        ),
    ]
