# Generated by Django 5.0.2 on 2024-05-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_arma_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='imageurl',
            field=models.ImageField(blank=True, null=True, upload_to='media/imgs'),
        ),
    ]
