# Generated by Django 5.0.2 on 2024-05-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_arma_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='imageurl',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to='media/imgs'),
        ),
    ]
