# Generated by Django 5.0.2 on 2024-05-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_arma_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='imageurl',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
