# Generated by Django 5.0.2 on 2024-05-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_arma_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
