# Generated by Django 5.0.2 on 2024-05-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_arma_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='inspect_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
