# Generated by Django 5.0.2 on 2024-05-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_arma_inspect_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='inspect_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
