# Generated by Django 5.0.2 on 2024-07-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_arma_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='habilitada',
            field=models.BooleanField(default=True),
        ),
    ]
