# Generated by Django 5.0.2 on 2024-07-07 23:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_remove_carrito_contenido_carrito_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaccion_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_de_compra', models.DateTimeField(verbose_name='Fecha de compra')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada'), ('Completada', 'Completada')], default='Pendiente', max_length=10)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
