# Generated by Django 5.0.2 on 2024-05-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='user', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
