# Generated by Django 5.0.2 on 2024-05-08 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email']},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
